<?php
/**
 * Sigma SMS A2P — Configuration
 *
 * Auto-generated by install.php, or manually edited.
 * Railway: set MYSQLHOST, MYSQLDATABASE, MYSQLUSER, MYSQLPASSWORD env vars.
 */

// ── Database ─────────────────────────────────────────────────────────────────
define('DB_HOST',    getenv('MYSQLHOST')     ?: getenv('DB_HOST')  ?: 'localhost');
define('DB_PORT',    getenv('MYSQLPORT')     ?: getenv('DB_PORT')  ?: '3306');
define('DB_NAME',    getenv('MYSQLDATABASE') ?: getenv('DB_NAME')  ?: 'sigma_sms_a2p');
define('DB_USER',    getenv('MYSQLUSER')     ?: getenv('DB_USER')  ?: 'root');
define('DB_PASS',    getenv('MYSQLPASSWORD') ?: getenv('DB_PASS')  ?: '');
define('DB_CHARSET', 'utf8mb4');
define('DB_SSL_MODE', getenv('DB_SSL_MODE') ?: 'preferred');

// ── Application ──────────────────────────────────────────────────────────────
define('APP_NAME',    'Sigma SMS A2P');
define('APP_VERSION', '1.0.0');

if (!defined('APP_URL')) {
    $appUrlEnv = getenv('APP_URL') ?: '';
    if ($appUrlEnv) {
        // Explicit env var — highest priority (set this in Railway dashboard)
        define('APP_URL', rtrim($appUrlEnv, '/'));
    } else {
        // Auto-detect: on Railway the doc root IS sigma_sms/, so no subfolder
        $proto = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
        // Railway proxies HTTPS — check forwarded header too
        if (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https') $proto = 'https';
        $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
        $path = rtrim(dirname($_SERVER['PHP_SELF'] ?? '/'), '/\\');
        // If doc root is sigma_sms/ directly (Railway/Docker), path is '' or '/'
        define('APP_URL', ($path === '' || $path === '/' || $path === '\\')
            ? "$proto://$host"
            : "$proto://$host$path"
        );
    }
}

// ── OTP API ──────────────────────────────────────────────────────────────────
define('OTP_API_URL',        'https://tempnum.net/api/public/otps');
define('OTP_FETCH_INTERVAL', 60);

// ── Session ──────────────────────────────────────────────────────────────────
define('SESSION_LIFETIME', 86400);

// ── Timezone / Errors ────────────────────────────────────────────────────────
date_default_timezone_set('UTC');
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// ── PDO connection (singleton) ────────────────────────────────────────────────
function getDB(): PDO {
    static $pdo = null;
    if ($pdo !== null) return $pdo;

    // ── Check pdo_mysql extension ────────────────────────────────────────────
    if (!extension_loaded('pdo_mysql')) {
        _db_fatal_error(
            'Missing PHP extension: <code>pdo_mysql</code>',
            _missing_extension_help()
        );
    }

    $dsnAndCreds = buildPdoDsnAndCredentials();
    $options = [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
    ];

    try {
        $pdo = new PDO($dsnAndCreds['dsn'], $dsnAndCreds['user'], $dsnAndCreds['pass'], $options);
    } catch (PDOException $e) {
        _db_fatal_error(
            'Database connection failed',
            '<p><strong>Error:</strong> ' . htmlspecialchars($e->getMessage()) . '</p>'
            . '<p>Check that your DB credentials in <code>config.php</code> are correct, '
            . 'and that the MySQL server is reachable from this host.</p>'
            . '<p><a href="' . APP_URL . '/install.php" style="color:#4f46e5;">Re-run the installer</a></p>'
        );
    }

    return $pdo;
}

function buildPdoDsnAndCredentials(): array {
    $databaseUrl = getenv('DATABASE_URL') ?: '';
    if ($databaseUrl) {
        $parsed = parse_url($databaseUrl);
        if (is_array($parsed) && !empty($parsed['host']) && !empty($parsed['path'])) {
            $host = $parsed['host'];
            $port = (string)($parsed['port'] ?? 3306);
            $dbName = ltrim($parsed['path'], '/');
            $charset = DB_CHARSET;
            $user = $parsed['user'] ?? DB_USER;
            $pass = $parsed['pass'] ?? DB_PASS;
            return [
                'dsn' => "mysql:host={$host};port={$port};dbname={$dbName};charset={$charset}",
                'user' => $user,
                'pass' => $pass,
            ];
        }
    }

    return [
        'dsn' => 'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET,
        'user' => DB_USER,
        'pass' => DB_PASS,
    ];
}

/**
 * Show a human-readable fatal error page and exit.
 * Works for both HTML page requests and JSON/AJAX requests.
 */
function _db_fatal_error(string $title, string $detail): never {
    $isAjax = (
        !empty($_SERVER['HTTP_X_REQUESTED_WITH']) ||
        str_contains($_SERVER['HTTP_ACCEPT'] ?? '', 'application/json') ||
        str_contains($_SERVER['PHP_SELF'] ?? '', '/ajax/') ||
        str_contains($_SERVER['PHP_SELF'] ?? '', '/api/')
    );

    http_response_code(500);

    if ($isAjax) {
        header('Content-Type: application/json');
        echo json_encode(['error' => strip_tags($title), 'detail' => strip_tags($detail)]);
        exit;
    }

    echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Configuration Error — Sigma SMS A2P</title>
<style>
*{box-sizing:border-box}
body{margin:0;font-family:system-ui,sans-serif;background:#f1f5f9;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:1rem}
.box{background:#fff;border-radius:14px;box-shadow:0 4px 24px rgba(0,0,0,.1);padding:2rem;max-width:640px;width:100%}
h2{color:#dc2626;margin:0 0 1rem;font-size:1.2rem;display:flex;align-items:center;gap:.5rem}
.detail{background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:1rem;font-size:.875rem;color:#7f1d1d;line-height:1.6}
.detail code{background:#fee2e2;padding:.1em .3em;border-radius:3px;font-size:.9em}
.detail pre{background:#1e293b;color:#e2e8f0;padding:1rem;border-radius:8px;overflow-x:auto;font-size:.82rem;margin:.75rem 0 0}
</style></head><body>
<div class="box">
  <h2>⚠️ ' . htmlspecialchars($title) . '</h2>
  <div class="detail">' . $detail . '</div>
</div>
</body></html>';
    exit;
}

/**
 * Returns help HTML for the missing pdo_mysql extension.
 */
function _missing_extension_help(): string {
    $os = PHP_OS_FAMILY;
    return '
<p>The <code>pdo_mysql</code> PHP extension is required but not loaded.</p>
<p><strong>PHP version:</strong> ' . PHP_VERSION . ' &nbsp;|&nbsp; <strong>OS:</strong> ' . htmlspecialchars($os) . '</p>

<p><strong>How to fix — choose your environment:</strong></p>

<p><strong>Ubuntu / Debian:</strong></p>
<pre>sudo apt-get install php' . PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '-mysql
sudo service apache2 restart   # or: sudo service php-fpm restart</pre>

<p><strong>CentOS / RHEL / AlmaLinux:</strong></p>
<pre>sudo yum install php-mysqlnd
sudo systemctl restart httpd</pre>

<p><strong>Windows (XAMPP / WAMP):</strong></p>
<pre>Open php.ini, find and uncomment:
;extension=pdo_mysql   →   extension=pdo_mysql
Then restart Apache.</pre>

<p><strong>Docker / Railway:</strong></p>
<pre># In your Dockerfile:
RUN docker-php-ext-install pdo pdo_mysql</pre>

<p><strong>Shared hosting (cPanel):</strong><br>
Go to <em>PHP Selector</em> → enable <code>pdo_mysql</code> → Save.</p>

<p>After enabling the extension, <a href="' . APP_URL . '/install.php" style="color:#4f46e5;font-weight:600;">run the installer again</a>.</p>';
}

// ── Session initialization ────────────────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    $isSecure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
             || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');
    session_set_cookie_params([
        'lifetime' => SESSION_LIFETIME,
        'path'     => '/',
        'secure'   => $isSecure,
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
}
